### PR TITLE
Point turn bug fix

### PR DESCRIPTION
**Pull request by iamef**
Moved setPower(power) to after isClockwise initialization so the robot turns in the proper direction
And after power may have set to stall power if angle < 45 degrees

### CODE REVIEW

**Comment by AG6GR** [comment]
Looks like you've got duplicate commits. Try `git checkout e1d2bf4` (choose the first commit), `git branch -f PointTurnBugFix` (Force move the branch PointTurnBugFix to that commit), `git push -f origin PointTurnBugFix` (Push the moved branch to github)

**Comment by iamef** [comment]
The reason for the duplicate commits is because I tried doing git commit --amend -m"" which requires me to merge and somehow duplicates the commits. 

Thanks @AG6GR for the suggestion! I really enjoyed working with you throughout robotics.

**Comment by AG6GR** [comment]
No problem, whenever you need to edit existing commits, the best tool is the interactive rebase `git rebase -i <target>`. This is a good guide: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by AG6GR** [comment]
Somehow this is a duplicate of pull request #8

**Pull request closed without merging**
